/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TierlistRouteImport } from './routes/tierlist'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSyncTiersRouteImport } from './routes/api/public/sync-tiers'
import { Route as ApiPublicBotTiersRouteImport } from './routes/api/public/bot-tiers'

const TierlistRoute = TierlistRouteImport.update({
  id: '/tierlist',
  path: '/tierlist',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncTiersRoute = ApiPublicSyncTiersRouteImport.update({
  id: '/api/public/sync-tiers',
  path: '/api/public/sync-tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotTiersRoute = ApiPublicBotTiersRouteImport.update({
  id: '/api/public/bot-tiers',
  path: '/api/public/bot-tiers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/tierlist': typeof TierlistRoute
  '/api/public/bot-tiers': typeof ApiPublicBotTiersRoute
  '/api/public/sync-tiers': typeof ApiPublicSyncTiersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/tierlist': typeof TierlistRoute
  '/api/public/bot-tiers': typeof ApiPublicBotTiersRoute
  '/api/public/sync-tiers': typeof ApiPublicSyncTiersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/tierlist': typeof TierlistRoute
  '/api/public/bot-tiers': typeof ApiPublicBotTiersRoute
  '/api/public/sync-tiers': typeof ApiPublicSyncTiersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/tierlist'
    | '/api/public/bot-tiers'
    | '/api/public/sync-tiers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/tierlist'
    | '/api/public/bot-tiers'
    | '/api/public/sync-tiers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/leaderboard'
    | '/tierlist'
    | '/api/public/bot-tiers'
    | '/api/public/sync-tiers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LeaderboardRoute: typeof LeaderboardRoute
  TierlistRoute: typeof TierlistRoute
  ApiPublicBotTiersRoute: typeof ApiPublicBotTiersRoute
  ApiPublicSyncTiersRoute: typeof ApiPublicSyncTiersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tierlist': {
      id: '/tierlist'
      path: '/tierlist'
      fullPath: '/tierlist'
      preLoaderRoute: typeof TierlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-tiers': {
      id: '/api/public/sync-tiers'
      path: '/api/public/sync-tiers'
      fullPath: '/api/public/sync-tiers'
      preLoaderRoute: typeof ApiPublicSyncTiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot-tiers': {
      id: '/api/public/bot-tiers'
      path: '/api/public/bot-tiers'
      fullPath: '/api/public/bot-tiers'
      preLoaderRoute: typeof ApiPublicBotTiersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LeaderboardRoute: LeaderboardRoute,
  TierlistRoute: TierlistRoute,
  ApiPublicBotTiersRoute: ApiPublicBotTiersRoute,
  ApiPublicSyncTiersRoute: ApiPublicSyncTiersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
